### ISSUE TITLE
Prepare for upcoming release

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/oxlint-ecosystem-ci#33]
## Todo
- [ ] Publish migration guide on `oxc-project.github.io` repo

## Pending Ecosystem PRs
- [x] https://github.com/rolldown/rolldown/pull/2432
- [x] https://github.com/toeverything/AFFiNE/pull/8494
- [x] https://github.com/preactjs/preact/pull/4533
